# Generated by Django 5.2 on 2025-04-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='PickUpSpot',
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
