# Generated by Django 5.2 on 2025-05-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_address_pickupspot_delete_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
